name = "internetku"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "80d23b9f-3d72-40b2-a7b7-2053404202fb"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
